[package]
name = "tyler"
version = "0.4.1"
edition = "2021"
authors = ["Balázs Dukai <balazs.dukai@3dgi.nl>", "Ravi Peters <ravi.peters@3dgi.nl>"]
description = "Create tiles from 3D city objects encoded as CityJSONFeatures."
repository = "https://github.com/3DGI/tyler"
homepage = "https://github.com/3DGI/tyler"
documentation = "https://github.com/3DGI/tyler"
readme = "README.md"
license = "Apache-2.0"
keywords = ["geo", "cityjson"]
categories = ["command-line-utilities", "science::geo"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "tyler"
path = "src/main.rs"

[dependencies]
mimalloc = "0.1"
cityjson-lib = { version = "0.9.0", features = ["json"] }
cityjson-index = { version = "0.9.0" }
cityjson-convert = { version = "0.1.0" }
log = "0.4.17"
env_logger = "0.10.0"
clap = { version = "4.0.32", features = ["cargo", "derive"] }
serde = { version = "1.0.152", features = ["derive"] }
serde_json = "1.0.91"
serde_repr = "0.1.10"
rayon = "1.6.1"
bitvec = "1.0.1"
morton-encoding = "2.0.1"
bincode = "1.3.3"
proj-sys = { version = "0.23.1", features = ["network"] } # remove after tyler/develop is merged
libc = "0.2.119" # remove after tyler/develop is merged
num-traits = "0.2.14" # remove after tyler/develop is merged
thiserror = "1.0.30" # remove after tyler/develop is merged

[workspace]
members = [".", "cityjson-convert"]
resolver = "2"

[patch.crates-io]
cityjson-convert = { path = "cityjson-convert" }
cityjson-lib = { git = "https://github.com/3DGI/cityjson-rs.git", branch = "main" }
cityjson-index = { git = "https://github.com/3DGI/cityjson-rs.git", branch = "main" }
cityjson-types = { git = "https://github.com/3DGI/cityjson-rs.git", branch = "main" }
cityjson-json = { git = "https://github.com/3DGI/cityjson-rs.git", branch = "main" }
