on:
  release:
    types:
      - published

name: Docker build
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - uses: elgohr/Publish-Docker-Github-Action@v5
        env:
          VERSION: ${{ github.ref }}
        with:
          name: "3dgi/tyler"
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          dockerfile: docker/tyler.dockerfile
          tag_semver: true
          buildargs: VERSION
