on:
  release:
    types:
      - published

name: Docker build
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        submodules: true
      - uses: elgohr/Publish-Docker-Github-Action@v5
        with:
          name: "${{ env.GITHUB_REPOSITORY }}/tyler"
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ghcr.io
          dockerfile: docker/tyler.dockerfile
          tag_semver: true
